# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a base
FROM node:alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for installing dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Prepare a lightweight production image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy the built code and node_modules from the builder
COPY --from=builder /app/build /app/build
COPY --from=builder /app/node_modules /app/node_modules
COPY package.json ./

# Set environment variables (to be replaced by actual values or through Docker environment settings)
ENV SHOPIFY_ACCESS_TOKEN=<your_access_token>
ENV MYSHOPIFY_DOMAIN=<your_shop>.myshopify.com

# Expose the necessary port (if applicable, modify as needed)
# EXPOSE 3000

# Run the application
CMD ["node", "build/index.js"]
